TrabajoPractico1.1/Controllers/peliculasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL;
using DAL.ModelViews;
using DAL.Servicios;

namespace TrabajoPractico.Controllers
{
    public class peliculasController : Controller
    {
        ContextoPractico ctx = new ContextoPractico();
        // GET: /peliculas/

        public ActionResult reserva(int id)
        {
            sReservas reservaServ = new sReservas();
            vReserva reserva = new vReserva();

            reserva.IdPelicula = id;
            reserva = reservaServ.cargarVersiones(reserva);

            return View(reserva);
        }

        [HttpPost]
        public ActionResult reserva(FormCollection form, vReserva myReserva)
        {
            sReservas reservaServ = new sReservas();

            myReserva = reservaServ.cargarVersiones(myReserva);
            myReserva = reservaServ.cargarSedes(myReserva);
            myReserva = reservaServ.cargarDias(myReserva);
            myReserva = reservaServ.cargarHorarios(myReserva);
            //verifica que este cargada la funcion y se haya apretado el submit
            if (Request.Form["btnComprar"] != null && myReserva.FechaHora != null)
            {
                Reservas confirmacion = reservaServ.crearSesionReserva(myReserva);
                Session["reserva"] = confirmacion;
                return RedirectToAction("confirmar");
            }
            return View(myReserva);
        }

        public ActionResult confirmar()
        {
            sPeliculas sConfirma = new sPeliculas();
            Reservas sesion = Session["reserva"] as Reservas;

            ViewBag.confirmacion = sConfirma.llenarVista(sesion);
            ViewBag.TiposDocumentos = ctx.TiposDocumentos.ToList();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult confirmarPelicula(Reservas myReserva)
        {
            if (ModelState.IsValid)
            {
                sPeliculas confirmarServ = new sPeliculas();

                myReserva = confirmarServ.completarReserva(Session["reserva"] as Reservas, myReserva);

                Session.Remove("reserva");

                var Datos = ctx.Sedes.Where(x => x.IdSede == myReserva.IdSede).FirstOrDefault();

                ViewBag.CodigoReserva = myReserva.IdReserva;
                ViewBag.Precio = "$" + (Datos.PrecioGeneral * myReserva.CantidadEntradas).ToString();
                ViewBag.CantidadEntradas = myReserva.CantidadEntradas;

                return View("confirmar");
            }
            return RedirectToAction("Inicio", "home"); ;
        }

    }
}

TrabajoPractico1.1/Views/peliculas/confirmar.cshtml
@using DAL
@using DAL.ModelViews
@model Reservas

@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Confirmacion";
}

@if (ViewBag.confirmacion != null)
{//Entra cuando trae los datos de confirmacion
    <div class="col-md-5 col-md-offset-3">
        <div class="panel-body panel panel-info">
            <div class="form-group panel-primary">
                <div class="text-center panel-heading">
                    <h5>Reserva</h5>
                </div>
            </div>
            @{vConfirmacion Datos = ViewBag.confirmacion as vConfirmacion;}
            <div class="form-group">
                <div class="col-md-9 ">
                    <div id="titulo">@Datos.pelicula.Nombre </div>
                    <div id="descripcion">@Datos.pelicula.Descripcion</div>
                    <div id="genero">@Datos.pelicula.Generos.Nombre</div>
                    <div id="clasificacion">@Datos.pelicula.Calificaciones.Nombre</div>
                    <div id="precio">$ @Datos.cartelera.Sedes.PrecioGeneral</div>
                    <div id="version">@Datos.cartelera.Versiones.Nombre</div>
                    <div id="sede">@Datos.cartelera.Sedes.Nombre </div>
                    <div id="dia">@Datos.FechaHoraInicio </div>
                </div>
                <img class="pelicula" src=@Datos.pelicula.Imagen />    
            </div>
            @using (Html.BeginForm("confirmarPelicula", "peliculas", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-group">
                    <div class="form-control">
                        @Html.TextBox("Email", "", new { @placeholder = "Email" })
                    </div>
                    @Html.ValidationMessage("Email")
                </div>
                <div class="form-group">
                    <div class="form-control">
                        @Html.DropDownList("IdTipoDocumento", new SelectList(ViewBag.TiposDocumentos, "IdTipoDocumento", "Descripcion"))
                    </div>
                    @Html.ValidationMessage("IdTipoDocumento")
                </div>
                <div class="form-group">
                    <div class="form-control">
                        @Html.TextBox("NumeroDocumento", "", new { @placeholder = "Documento" })
                    </div>
                    @Html.ValidationMessage("NumeroDocumento")
                </div>
                <div class="form-group">
                    <div class="form-control">
                        @Html.TextBox("CantidadEntradas", "", new { @placeholder = "Entradas" })
                    </div>
                    @Html.ValidationMessage("CantidadEntradas")
                </div>

                <input type="submit" value="Confirmar Compra" class="btn btn-info btn-lg btn-block" /><br /><br />
            }
            <div class="form-group">
                <div class="alert alert-info text-center">
                    <h5>la reserva estará vigente hasta 1hr antes de la función elegida y deberá ser confirmada en el cine seleccionado</h5>
                </div>
            </div>
        </div>
    </div>
}
else if (ViewBag.CodigoReserva != null)
{//Entra si Se guardo La reserva
    <div class="form-group">
        <div class="alert alert-info text-center">
            <h5>Codigo Reserva: @ViewBag.CodigoReserva</h5>
            <h5>Importe Total: @ViewBag.Precio</h5>
            <h5>Cantidad Entradas: @ViewBag.CantidadEntradas</h5>
            <h4>la reserva estará vigente hasta 1hr antes de la función elegida y deberá ser confirmada en el cine seleccionado</h4>
        </div>
    </div>
    <a href="/home/Inicio" class="col-sm-2  btn btn-primary">finaliza</a>
}

TrabajoPractico1.1/Views/peliculas/reserva.cshtml
@using DAL.ModelViews
@model vReserva
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Reservar";
}

<section>
    @if (Model.Versiones.Count() > 0)
    {
        <div class="col-md-5 col-md-offset-3">
            <div class="panel-body panel panel-info">
                <div class="form-group panel-primary">
                    <div class="text-center panel-heading">
                        <h5>Bienvenido al panel de reservas</h5>
                    </div>
                </div>
                @using (Html.BeginForm("reserva", "peliculas", FormMethod.Post))
                {
                    @Html.HiddenFor(x => x.IdPelicula, Model.IdPelicula)
                    <div class="form-group">
                        <div class="form-control">
                            @Html.DropDownListFor(x => x.idVersion, new SelectList(Model.Versiones, "IdVersion", "Nombre"), "--Seleccione region--")
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-control">
                            @Html.DropDownListFor(x => x.idSede, new SelectList(Model.Sedes, "IdSede", "Nombre"), "--Seleccione Sede--")
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-control">
                            @Html.DropDownListFor(x => x.Dia, new SelectList(Model.Dias), "--Seleccione Dia--")
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-control">
                            @Html.DropDownListFor(x => x.FechaHora, new SelectList(Model.Horarios), "--Seleccione Hora--")
                        </div>
                    </div>
                    
                    <button type="submit" name="btnComprar"  class="btn btn-info">Confirmar Reserva</button><br /><br />
                }
            </div>
        </div>
    }
    else
    {
        <h3>La Pelicula Seleccionada no Tiene funciones disponibles</h3>
        <a href="/home/Inicio"> <div class="reservar2">Volver</div> </a>
    }

</section>

@section scripts
{
    <script src="~/Scripts/reserva.js"></script>
}